//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGioHang
    {
        public int ChitiethiohangID { get; set; }
        public Nullable<int> GiohangkhID { get; set; }
        public Nullable<int> Masach { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> Thanhtien { get; set; }
    
        public virtual Giohangkh Giohangkh { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
