//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giohangkh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giohangkh()
        {
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public int GiohangkhID { get; set; }
        public Nullable<int> Makh { get; set; }
        public Nullable<System.DateTime> Ngaymua { get; set; }
        public Nullable<int> Tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}
